### ISSUE TITLE
Application stopped working

### ISSUE THREAD

**Issue by Cranbaerry** [book000/ZoomInClass#3]
The app stopped working and closes itself as soon as it was open.
I cannot see ZoomInClass.exe in Task Manager.
There was no logs available to help.

**Comment by book000** [comment]
Thank you for sending me the issue.

Can you please give me your computer information and situation as follows so that I can check?

- **OS version**: Screenshot of the window displayed by the `winver` command.
- **Discord client version**: You can find it at the bottom of Discord user settings.
- When you start ZoomInClass, is Discord running?
- In Discord settings, under `Activity Status`, is `Display currect activity as a status message.` turned on?

**Comment by Cranbaerry** [comment]
- OS version: 20H2 (OS Build 19042.1110)
- Discord version: Stable 92214 (db690ab)
- Yes
- Yes

**Comment by book000** [comment]
Thanks for the reply.

Thank you for letting me know about your computer information and status. I think appears that you have met the basic requirements regarding execution.

I recently released a new version that adds error handling and debug mode, and fixes one bug: https://github.com/book000/ZoomInClass/releases/tag/v1.0.2
Please download this release and follow the steps below to collect bug information. (I'd be even happier if they fixed the bug that prevented it from working)

1. Extract the ZIP file and place it in the desired location.
2. Open ZoomInClass.exe normally in Windows Explorer and see if it closes immediately.
  If it doesn't close right away and works properly, the bug is fixed!
3. If you see an error dialog, please give me a screenshot of that dialog.
4. If you don't get an error dialog and it's not working, try typing `cmd` in the address field of Windows Explorer to start a command prompt, and then type `ZoomInClass.exe --debug` to start it in debug mode!
  ![image](https://user-images.githubusercontent.com/8929706/128233581-50f1d746-0913-47b3-89ea-fb222eff2ee6.png)
5. Then, please wait for about 10 seconds after starting debug mode and send me the displayed contents.

I look forward to hearing from you.

**Comment by Cranbaerry** [comment]
Hello, it's working now! Thank you.
